fix single card

diff --git a/.github/workflows/ce_cuda129_dev.yaml b/.github/workflows/ce_cuda129_dev.yaml
--- a/.github/workflows/ce_cuda129_dev.yaml
+++ b/.github/workflows/ce_cuda129_dev.yaml
@@ -39,183 +39,183 @@ defaults:
     shell: bash
 
 jobs:
-  single_card_test:
-    name: Unit test (single card)
-    runs-on:
-      group: Fleet-H-single-card
-    env:
-      PIP_CACHE_DIR: /home/.cache/pip
-      CACHE_DIR: /home/.cache
-      TASK: paddlefleet-CE-CUDA129-DEV-single-card-test
-    steps:
-      - name: Determine the runner
-        run: |
-          gpu_id=$(( $(echo $PWD | awk -F'/' '{print $3}' | awk -F'-' '{print $2}') + 3 ))
-          echo GPU_DEVICES="$gpu_id" >> $GITHUB_ENV
+  # single_card_test:
+  #   name: Unit test (single card)
+  #   runs-on:
+  #     group: Fleet-H-single-card
+  #   env:
+  #     PIP_CACHE_DIR: /home/.cache/pip
+  #     CACHE_DIR: /home/.cache
+  #     TASK: paddlefleet-CE-CUDA129-DEV-single-card-test
+  #   steps:
+  #     - name: Determine the runner
+  #       run: |
+  #         gpu_id=$(( $(echo $PWD | awk -F'/' '{print $3}' | awk -F'-' '{print $2}') + 3 ))
+  #         echo GPU_DEVICES="$gpu_id" >> $GITHUB_ENV
 
-      - name: Check docker image and run container
-        env:
-          GPU_DEVICES: ${{ env.GPU_DEVICES }}
-        run: |
-          container_name=${TASK}-$(date +%Y%m%d-%H%M%S)
-          echo "container_name=${container_name}" >> ${{ github.env }}
-          docker pull $docker_image
-          docker run -d -t --name ${container_name} --gpus "\"device=${GPU_DEVICES}\"" --shm-size=32G \
-            -v "/dev/shm:/dev/shm"  \
-            -v ${{ github.workspace }}/../../..:${{ github.workspace }}/../../.. \
-            -v ${{ github.workspace }}/../../..:/root \
-            -v /ssd1/paddle-1/action_cache:/home/.cache \
-            -v ${{ github.workspace }}:/paddle \
-            -e BRANCH \
-            -e PR_ID \
-            -e COMMIT_ID \
-            -e PADDLE_ROOT \
-            -e repo_flag="paddlefleet" \
-            -e ci_scripts \
-            -e use_release \
-            -e CACHE_DIR \
-            -e no_proxy \
-            -e CI_name \
-            -e PIP_CACHE_DIR \
-            -e work_dir \
-            -e GITHUB_HEAD_REF="${{ github.head_ref }}" \
-            -e GITHUB_REPO_NAME="${{ github.repository }}" \
-            -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
-            -e GITHUB_RUN_ID="${{ github.run_id }}" \
-            -w /paddle --network host ${docker_image}
+  #     - name: Check docker image and run container
+  #       env:
+  #         GPU_DEVICES: ${{ env.GPU_DEVICES }}
+  #       run: |
+  #         container_name=${TASK}-$(date +%Y%m%d-%H%M%S)
+  #         echo "container_name=${container_name}" >> ${{ github.env }}
+  #         docker pull $docker_image
+  #         docker run -d -t --name ${container_name} --gpus "\"device=${GPU_DEVICES}\"" --shm-size=32G \
+  #           -v "/dev/shm:/dev/shm"  \
+  #           -v ${{ github.workspace }}/../../..:${{ github.workspace }}/../../.. \
+  #           -v ${{ github.workspace }}/../../..:/root \
+  #           -v /ssd1/paddle-1/action_cache:/home/.cache \
+  #           -v ${{ github.workspace }}:/paddle \
+  #           -e BRANCH \
+  #           -e PR_ID \
+  #           -e COMMIT_ID \
+  #           -e PADDLE_ROOT \
+  #           -e repo_flag="paddlefleet" \
+  #           -e ci_scripts \
+  #           -e use_release \
+  #           -e CACHE_DIR \
+  #           -e no_proxy \
+  #           -e CI_name \
+  #           -e PIP_CACHE_DIR \
+  #           -e work_dir \
+  #           -e GITHUB_HEAD_REF="${{ github.head_ref }}" \
+  #           -e GITHUB_REPO_NAME="${{ github.repository }}" \
+  #           -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
+  #           -e GITHUB_RUN_ID="${{ github.run_id }}" \
+  #           -w /paddle --network host ${docker_image}
 
 
-      - name: Single card test
-        run: |
-          docker exec -t ${{ env.container_name }} /bin/bash -xce '
-          pwd
-          rm -rf * .[^.]*
-          source /root/proxy
-          mkdir -p /home/.cache/pip
-          pip cache dir
-          echo "Install uv"
-          export WITH_COVERAGE=ON
-          pip install --upgrade pip
-          git clone https://github.com/PaddlePaddle/PaddleFleet.git .
-          git config --global --add safe.directory /paddle
-          git config user.name "PaddleCI"
-          git config user.email "paddle_ci@example.com"
-          git config pull.rebase false
-          pip install colorlog>=6.10.1
-          pip install nvidia-cutlass-dsl==4.2.1
-          python -m pip install --pre  paddlefleet --index-url https://www.paddlepaddle.org.cn/packages/nightly/cu129/ --extra-index-url https://www.paddlepaddle.org.cn/packages/stable/cu129/   --extra-index-url https://pypi.tuna.tsinghua.edu.cn/simple
-          if [ "${use_release}" == "true" ]; then
-            echo "Using pre-built paddle package from develop branch."
-            pip install https://paddle-qa.bj.bcebos.com/paddle-pipeline/Develop-GpuAll-LinuxCentos-Gcc11-Cuda129-Cudnn99-Trt105-Py310-Compile/latest/paddlepaddle_gpu-0.0.0-cp310-cp310-linux_x86_64.whl --index-url=https://www.paddlepaddle.org.cn/packages/nightly/cu129/ --force-reinstall --no-cache-dir
-          fi
-          pip install uv coverage==7.6.1 bce-python-sdk==0.8.74 wrapt matplotlib==3.10.8 pytest
-          echo "Paddle Commit"
-          python -c "import paddle; print(paddle.version.commit)"
-          echo "PaddleFleet Commit"
-          python -c "import paddlefleet; print(paddlefleet.version.commit)"
-          bash ci/single_card_test.sh
-          single_card_exit_code=$?
-          if [[ "$single_card_exit_code" != "0" ]]; then
-            echo -e "::error:: \033[31mSingle card test failed.\033[0m"
-            exit 1
-          else
-            echo -e "\033[32mSingle card test succeeded.\033[0m"
-          fi
-          '
+  #     - name: Single card test
+  #       run: |
+  #         docker exec -t ${{ env.container_name }} /bin/bash -xce '
+  #         pwd
+  #         rm -rf * .[^.]*
+  #         source /root/proxy
+  #         mkdir -p /home/.cache/pip
+  #         pip cache dir
+  #         echo "Install uv"
+  #         export WITH_COVERAGE=ON
+  #         pip install --upgrade pip
+  #         git clone https://github.com/PaddlePaddle/PaddleFleet.git .
+  #         git config --global --add safe.directory /paddle
+  #         git config user.name "PaddleCI"
+  #         git config user.email "paddle_ci@example.com"
+  #         git config pull.rebase false
+  #         pip install colorlog>=6.10.1
+  #         pip install nvidia-cutlass-dsl==4.2.1
+  #         python -m pip install --pre  paddlefleet --index-url https://www.paddlepaddle.org.cn/packages/nightly/cu129/ --extra-index-url https://www.paddlepaddle.org.cn/packages/stable/cu129/   --extra-index-url https://pypi.tuna.tsinghua.edu.cn/simple
+  #         if [ "${use_release}" == "true" ]; then
+  #           echo "Using pre-built paddle package from develop branch."
+  #           pip install https://paddle-qa.bj.bcebos.com/paddle-pipeline/Develop-GpuAll-LinuxCentos-Gcc11-Cuda129-Cudnn99-Trt105-Py310-Compile/latest/paddlepaddle_gpu-0.0.0-cp310-cp310-linux_x86_64.whl --index-url=https://www.paddlepaddle.org.cn/packages/nightly/cu129/ --force-reinstall --no-cache-dir
+  #         fi
+  #         pip install uv coverage==7.6.1 bce-python-sdk==0.8.74 wrapt matplotlib==3.10.8 pytest
+  #         echo "Paddle Commit"
+  #         python -c "import paddle; print(paddle.version.commit)"
+  #         echo "PaddleFleet Commit"
+  #         python -c "import paddlefleet; print(paddlefleet.version.commit)"
+  #         bash ci/single_card_test.sh
+  #         single_card_exit_code=$?
+  #         if [[ "$single_card_exit_code" != "0" ]]; then
+  #           echo -e "::error:: \033[31mSingle card test failed.\033[0m"
+  #           exit 1
+  #         else
+  #           echo -e "\033[32mSingle card test succeeded.\033[0m"
+  #         fi
+  #         '
 
-      - name: Terminate and delete the container
-        if: ${{ always() }}
-        run: |
-          set +e
-          docker exec -t ${{ env.container_name }} /bin/bash -c 'bash ci/clean_uv_cache.sh; rm -rf * .[^.]*'
-          docker rm -f ${{ env.container_name }}
+  #     - name: Terminate and delete the container
+  #       if: ${{ always() }}
+  #       run: |
+  #         set +e
+  #         docker exec -t ${{ env.container_name }} /bin/bash -c 'bash ci/clean_uv_cache.sh; rm -rf * .[^.]*'
+  #         docker rm -f ${{ env.container_name }}
 
-  multi-card_test:
-    name: Unit test (multi-card)
-    runs-on:
-      group: Fleet-H-multi-card
-    env:
-      PIP_CACHE_DIR: /home/.cache/pip
-      TASK: paddlefleet-CE-CUDA129-DEV-multi-card_test-release
-    steps:
-      - name: Check docker image and run container
-        run: |
-          container_name=${TASK}-$(date +%Y%m%d-%H%M%S)
-          echo "container_name=${container_name}" >> ${{ github.env }}
-          docker pull $docker_image
-          docker run -d -t --gpus all --name ${container_name} \
-            -v "/dev/shm:/dev/shm"  \
-            -v ${{ github.workspace }}/../../..:${{ github.workspace }}/../../.. \
-            -v ${{ github.workspace }}/../../..:/root \
-            -v /ssd1/paddle-1/action_cache:/home/.cache \
-            -v ${{ github.workspace }}:/paddle \
-            -e BRANCH \
-            -e PR_ID \
-            -e COMMIT_ID \
-            -e PADDLE_ROOT \
-            -e ci_scripts \
-            -e CACHE_DIR \
-            -e use_release \
-            -e no_proxy \
-            -e CI_name \
-            -e PIP_CACHE_DIR \
-            -e work_dir \
-            -e repo_flag="paddlefleet" \
-            -e GITHUB_SHA="${{ github.event.pull_request.head.sha }}" \
-            -e GITHUB_HEAD_REF="${{ github.head_ref }}" \
-            -e GITHUB_REPO_NAME="${{ github.repository }}" \
-            -e GITHUB_EVENT_NAME="${{ github.event_name }}" \
-            -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
-            -e GITHUB_RUN_ID="${{ github.run_id }}" \
-            -w /paddle --network host ${docker_image}
+  # multi-card_test:
+  #   name: Unit test (multi-card)
+  #   runs-on:
+  #     group: Fleet-H-multi-card
+  #   env:
+  #     PIP_CACHE_DIR: /home/.cache/pip
+  #     TASK: paddlefleet-CE-CUDA129-DEV-multi-card_test-release
+  #   steps:
+  #     - name: Check docker image and run container
+  #       run: |
+  #         container_name=${TASK}-$(date +%Y%m%d-%H%M%S)
+  #         echo "container_name=${container_name}" >> ${{ github.env }}
+  #         docker pull $docker_image
+  #         docker run -d -t --gpus all --name ${container_name} \
+  #           -v "/dev/shm:/dev/shm"  \
+  #           -v ${{ github.workspace }}/../../..:${{ github.workspace }}/../../.. \
+  #           -v ${{ github.workspace }}/../../..:/root \
+  #           -v /ssd1/paddle-1/action_cache:/home/.cache \
+  #           -v ${{ github.workspace }}:/paddle \
+  #           -e BRANCH \
+  #           -e PR_ID \
+  #           -e COMMIT_ID \
+  #           -e PADDLE_ROOT \
+  #           -e ci_scripts \
+  #           -e CACHE_DIR \
+  #           -e use_release \
+  #           -e no_proxy \
+  #           -e CI_name \
+  #           -e PIP_CACHE_DIR \
+  #           -e work_dir \
+  #           -e repo_flag="paddlefleet" \
+  #           -e GITHUB_SHA="${{ github.event.pull_request.head.sha }}" \
+  #           -e GITHUB_HEAD_REF="${{ github.head_ref }}" \
+  #           -e GITHUB_REPO_NAME="${{ github.repository }}" \
+  #           -e GITHUB_EVENT_NAME="${{ github.event_name }}" \
+  #           -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
+  #           -e GITHUB_RUN_ID="${{ github.run_id }}" \
+  #           -w /paddle --network host ${docker_image}
 
-      - name: Install PaddleFleet
-        run: |
-          docker exec -t ${{ env.container_name }} /bin/bash -ce '
-          rm -rf * .[^.]*
-          source /root/proxy
-          pip install --upgrade pip
-          git clone https://github.com/PaddlePaddle/PaddleFleet.git .
-          git config --global --add safe.directory /paddle
-          git config user.name "PaddleCI"
-          git config user.email "paddle_ci@example.com"
-          git config pull.rebase false
-          git submodule update --init --recursive
-          pip install colorlog>=6.10.1
-          pip install nvidia-cutlass-dsl==4.2.1
-          python -m pip install --pre  paddlefleet --index-url https://www.paddlepaddle.org.cn/packages/nightly/cu129/ --extra-index-url https://www.paddlepaddle.org.cn/packages/stable/cu129/   --extra-index-url https://pypi.tuna.tsinghua.edu.cn/simple
-          if [ "${use_release}" == "true" ]; then
-            echo "Using pre-built paddle package from develop branch."
-            pip install https://paddle-qa.bj.bcebos.com/paddle-pipeline/Develop-GpuAll-LinuxCentos-Gcc11-Cuda129-Cudnn99-Trt105-Py310-Compile/latest/paddlepaddle_gpu-0.0.0-cp310-cp310-linux_x86_64.whl --index-url=https://www.paddlepaddle.org.cn/packages/nightly/cu129/ --force-reinstall --no-cache-dir
-          fi
-          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
-          chmod +x /usr/local/bin/yq
-          '
+  #     - name: Install PaddleFleet
+  #       run: |
+  #         docker exec -t ${{ env.container_name }} /bin/bash -ce '
+  #         rm -rf * .[^.]*
+  #         source /root/proxy
+  #         pip install --upgrade pip
+  #         git clone https://github.com/PaddlePaddle/PaddleFleet.git .
+  #         git config --global --add safe.directory /paddle
+  #         git config user.name "PaddleCI"
+  #         git config user.email "paddle_ci@example.com"
+  #         git config pull.rebase false
+  #         git submodule update --init --recursive
+  #         pip install colorlog>=6.10.1
+  #         pip install nvidia-cutlass-dsl==4.2.1
+  #         python -m pip install --pre  paddlefleet --index-url https://www.paddlepaddle.org.cn/packages/nightly/cu129/ --extra-index-url https://www.paddlepaddle.org.cn/packages/stable/cu129/   --extra-index-url https://pypi.tuna.tsinghua.edu.cn/simple
+  #         if [ "${use_release}" == "true" ]; then
+  #           echo "Using pre-built paddle package from develop branch."
+  #           pip install https://paddle-qa.bj.bcebos.com/paddle-pipeline/Develop-GpuAll-LinuxCentos-Gcc11-Cuda129-Cudnn99-Trt105-Py310-Compile/latest/paddlepaddle_gpu-0.0.0-cp310-cp310-linux_x86_64.whl --index-url=https://www.paddlepaddle.org.cn/packages/nightly/cu129/ --force-reinstall --no-cache-dir
+  #         fi
+  #         wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
+  #         chmod +x /usr/local/bin/yq
+  #         '
 
-      - name: Multi-card test
-        run: |
-          docker exec -t ${{ env.container_name }} /bin/bash -ce '
-          echo "Paddle Commit"
-          python -c "import paddle; print(paddle.version.commit)"
-          echo "PaddleFleet Commit"
-          python -c "import paddlefleet; print(paddlefleet.version.commit)"
-          export PYTHONPATH=/paddle:$PYTHONPATH
-          bash ci/multi-card_test.sh
-          multi_card_exit_code=$?
-          if [[ "$multi_card_exit_code" != "0" ]]; then
-            echo -e "::error:: \033[31mMulti card test failed.\033[0m"
-            exit 1
-          else
-            echo -e "\033[32mMulti card test succeeded.\033[0m"
-          fi
-          '
+  #     - name: Multi-card test
+  #       run: |
+  #         docker exec -t ${{ env.container_name }} /bin/bash -ce '
+  #         echo "Paddle Commit"
+  #         python -c "import paddle; print(paddle.version.commit)"
+  #         echo "PaddleFleet Commit"
+  #         python -c "import paddlefleet; print(paddlefleet.version.commit)"
+  #         export PYTHONPATH=/paddle:$PYTHONPATH
+  #         bash ci/multi-card_test.sh
+  #         multi_card_exit_code=$?
+  #         if [[ "$multi_card_exit_code" != "0" ]]; then
+  #           echo -e "::error:: \033[31mMulti card test failed.\033[0m"
+  #           exit 1
+  #         else
+  #           echo -e "\033[32mMulti card test succeeded.\033[0m"
+  #         fi
+  #         '
 
-      - name: Terminate and delete the container
-        if: ${{ always() }}
-        run: |
-          set +e
-          docker exec -t ${{ env.container_name }} /bin/bash -c 'bash ci/clean_uv_cache.sh; rm -rf * .[^.]*'
-          docker rm -f ${{ env.container_name }}
+  #     - name: Terminate and delete the container
+  #       if: ${{ always() }}
+  #       run: |
+  #         set +e
+  #         docker exec -t ${{ env.container_name }} /bin/bash -c 'bash ci/clean_uv_cache.sh; rm -rf * .[^.]*'
+  #         docker rm -f ${{ env.container_name }}
 
 
   integration-test-H20-single-card:
@@ -316,7 +316,7 @@ jobs:
           '
 
       - name: Run single card integration test
-        uses: ./.github/actions/cases/single_card.yml
+        uses: ./.github/actions/single_card
         with:
           docker_name: ${{ env.container_name }}
           multi_python_version: ''
