fix

diff --git a/.github/workflows/ce_cuda_126_release.yml b/.github/workflows/ce_cuda_126_release.yml
--- a/.github/workflows/ce_cuda_126_release.yml
+++ b/.github/workflows/ce_cuda_126_release.yml
@@ -1,11 +1,8 @@
 name: CE-CUDA-126-Release
 
 on:
-  pull_request:
-    branches:
-      - develop
   schedule:
-    - cron: '0 19 * * *'
+    - cron: '0 19 * * 6'
   workflow_dispatch: # 可选：允许手动点 Run
 
 permissions: read-all
@@ -492,14 +489,8 @@ jobs:
           bash -x PaddleFormers/tests/integration_test/glm45_lora.sh
           glm45_exit_code=$?
           if [[ "$glm45_exit_code" != "0" ]]; then
-            wget https://paddle-qa.bj.bcebos.com/fleet/ce_cuda126_glm45_lora_loss.txt
-            python PaddleFormers/tests/integration_test/check_loss.py --log_file glm45_lora.txt --gt_file ce_cuda126_glm45_lora_loss.txt
-            if [[ "$?" != "0" ]]; then
-              echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
-              exit 1
-            else
-              echo -e "\033[32mIntegration test succeeded: GLM4.5.\033[0m"
-            fi
+            echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
+            exit 1
           else
             echo -e "\033[32mIntegration test succeeded: GLM4.5.\033[0m"
           fi
