fix

diff --git a/.github/workflows/check_pr.yml b/.github/workflows/check_pr.yml
--- a/.github/workflows/check_pr.yml
+++ b/.github/workflows/check_pr.yml
@@ -37,5 +37,8 @@ jobs:
           if cat changed_files.txt | grep -q "^D.*uv\.lock"; then
             echo "::error::uv.lock cannot be deleted in this PR"
             exit 1
+          else if cat changed_files.txt | grep -q "^R.*uv\.lock"; then
+            echo "::error::uv.lock cannot be renamed in this PR"
+            exit 1
           fi
           echo "uv.lock is intact"
