add sonic test

diff --git a/.github/workflows/cuda126_python_release.yml b/.github/workflows/cuda126_python_release.yml
--- a/.github/workflows/cuda126_python_release.yml
+++ b/.github/workflows/cuda126_python_release.yml
@@ -130,6 +130,30 @@ jobs:
           fi
           '
 
+      - name: Single card sonic moe test
+        if: matrix.python == '3.12'
+        run: |
+          docker exec -t ${{ env.container_name }} /bin/bash -xce '
+          pwd
+          rm -rf * .[^.]*
+          source /root/proxy
+          source "$HOME/miniconda/etc/profile.d/conda.sh"
+          conda activate python${{ matrix.python }}
+          echo "Paddle Commit"
+          python -c "import paddle; print(paddle.version.commit)"
+          echo "PaddleFleet Commit"
+          python -c "import paddlefleet; print(paddlefleet.version.commit)"
+          bash ci/single_card_sonic.sh
+          single_card_exit_code=$?
+          if [[ "$single_card_exit_code" != "0" ]]; then
+            echo -e "::error:: \033[31mSingle card test failed.\033[0m"
+            exit 1
+          else
+            echo -e "\033[32mSingle card test succeeded.\033[0m"
+          fi
+          '
+
+
       - name: Terminate and delete the container
         if: ${{ always() }}
         run: |
