fix

diff --git a/.github/workflows/Test.yml b/.github/workflows/Test.yml
--- a/.github/workflows/Test.yml
+++ b/.github/workflows/Test.yml
@@ -399,102 +399,102 @@ jobs:
           docker exec -t ${{ env.container_name }} /bin/bash -c 'rm -rf * .[^.]*'
           docker rm -f ${{ env.container_name }}
 
-integration-test:
-  needs: check-bypass
-  if: ${{ needs.check-bypass.outputs.can-skip != 'true' }}
-  name: Integration test (A100)
-  runs-on:
-    group: Distribute
-  env:
-    PIP_CACHE_DIR: /root/.cache/pip
-    CACHE_DIR: /root/.cache
-    TASK: paddlefleet-CI-${{ github.event.pull_request.number }}-integration-test-A100
-  steps:
-    - name: Check docker image and run container
-      if: ${{ matrix.name == 'H20' }}
-      run: |
-        container_name=${TASK}-$(date +%Y%m%d-%H%M%S)
-        echo "container_name=${container_name}" >> ${{ github.env }}
-        docker pull $docker_image
-        docker run -d -t --name ${container_name} --gpus all --shm-size=32G \
-          -v "/dev/shm:/dev/shm"  \
-          -v ${{ github.workspace }}/../../..:${{ github.workspace }}/../../.. \
-          -v ${{ github.workspace }}/../../../proxy:/root/proxy \
-          -v /ssd1/paddle-1/action_cache:/root/.cache \
-          -v ${{ github.workspace }}:/workspace \
-          -e BRANCH \
-          -e PR_ID \
-          -e COMMIT_ID \
-          -e work_dir \
-          -e PADDLE_ROOT \
-          -e ci_scripts \
-          -e CACHE_DIR \
-          -e no_proxy \
-          -e CI_name \
-          -e PIP_CACHE_DIR \
-          -e GITHUB_SHA="${{ github.event.pull_request.head.sha }}" \
-          -e GITHUB_HEAD_REF="${{ github.head_ref }}" \
-          -e GITHUB_BASE_SHA="${{ github.event.pull_request.base.sha }}" \
-          -e GITHUB_REPO_NAME="${{ github.repository }}" \
-          -e GITHUB_EVENT_NAME="${{ github.event_name }}" \
-          -e GITHUB_EVENT_PULL_REQUEST_NUMBER="${{ github.event.pull_request.number }}" \
-          -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
-          -e GITHUB_RUN_ID="${{ github.run_id }}" \
-          -w /workspace --network host ${docker_image}
+  integration-test-a100:
+    needs: check-bypass
+    if: ${{ needs.check-bypass.outputs.can-skip != 'true' }}
+    name: Integration test (A100)
+    runs-on:
+      group: Distribute
+    env:
+      PIP_CACHE_DIR: /root/.cache/pip
+      CACHE_DIR: /root/.cache
+      TASK: paddlefleet-CI-${{ github.event.pull_request.number }}-integration-test-A100
+    steps:
+      - name: Check docker image and run container
+        if: ${{ matrix.name == 'H20' }}
+        run: |
+          container_name=${TASK}-$(date +%Y%m%d-%H%M%S)
+          echo "container_name=${container_name}" >> ${{ github.env }}
+          docker pull $docker_image
+          docker run -d -t --name ${container_name} --gpus all --shm-size=32G \
+            -v "/dev/shm:/dev/shm"  \
+            -v ${{ github.workspace }}/../../..:${{ github.workspace }}/../../.. \
+            -v ${{ github.workspace }}/../../../proxy:/root/proxy \
+            -v /ssd1/paddle-1/action_cache:/root/.cache \
+            -v ${{ github.workspace }}:/workspace \
+            -e BRANCH \
+            -e PR_ID \
+            -e COMMIT_ID \
+            -e work_dir \
+            -e PADDLE_ROOT \
+            -e ci_scripts \
+            -e CACHE_DIR \
+            -e no_proxy \
+            -e CI_name \
+            -e PIP_CACHE_DIR \
+            -e GITHUB_SHA="${{ github.event.pull_request.head.sha }}" \
+            -e GITHUB_HEAD_REF="${{ github.head_ref }}" \
+            -e GITHUB_BASE_SHA="${{ github.event.pull_request.base.sha }}" \
+            -e GITHUB_REPO_NAME="${{ github.repository }}" \
+            -e GITHUB_EVENT_NAME="${{ github.event_name }}" \
+            -e GITHUB_EVENT_PULL_REQUEST_NUMBER="${{ github.event.pull_request.number }}" \
+            -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
+            -e GITHUB_RUN_ID="${{ github.run_id }}" \
+            -w /workspace --network host ${docker_image}
 
-    - name: Install PaddleFleet
-      if: ${{ matrix.name == 'H20' }}
-      run: |
-        docker exec -t ${{ env.container_name }} /bin/bash -ce '
-        rm -rf * .[^.]*
-        source /root/proxy
-        git clone https://github.com/PaddlePaddle/PaddleFleet.git
-        cd PaddleFleet
-        git config --global --add safe.directory /workspace/PaddleFleet
-        git config user.name "PaddleCI"
-        git config user.email "paddle_ci@example.com"
-        git config pull.rebase false
-        git pull --no-edit origin pull/${PR_ID}/head
-        mkdir -p /root/.cache/pip
-        pip cache dir
-        pip install --upgrade pip
-        pip install uv
-        uv sync -v
-        '
+      - name: Install PaddleFleet
+        if: ${{ matrix.name == 'H20' }}
+        run: |
+          docker exec -t ${{ env.container_name }} /bin/bash -ce '
+          rm -rf * .[^.]*
+          source /root/proxy
+          git clone https://github.com/PaddlePaddle/PaddleFleet.git
+          cd PaddleFleet
+          git config --global --add safe.directory /workspace/PaddleFleet
+          git config user.name "PaddleCI"
+          git config user.email "paddle_ci@example.com"
+          git config pull.rebase false
+          git pull --no-edit origin pull/${PR_ID}/head
+          mkdir -p /root/.cache/pip
+          pip cache dir
+          pip install --upgrade pip
+          pip install uv
+          uv sync -v
+          '
 
-    - name: Install PaddleFormers
-      if: ${{ matrix.name == 'H20' }}
-      run: |
-        docker exec -t ${{ env.container_name }} /bin/bash -ce '
-        source /root/proxy
-        git clone https://github.com/PaddlePaddle/PaddleFormers.git
-        cd PaddleFormers
-        git config --global --add safe.directory /workspace/PaddleFormers
-        git config user.name "PaddleCI"
-        git config user.email "paddle_ci@example.com"
-        git config pull.rebase false
-        source ../PaddleFleet/.venv/bin/activate
-        pip install -e .
-        '
+      - name: Install PaddleFormers
+        if: ${{ matrix.name == 'H20' }}
+        run: |
+          docker exec -t ${{ env.container_name }} /bin/bash -ce '
+          source /root/proxy
+          git clone https://github.com/PaddlePaddle/PaddleFormers.git
+          cd PaddleFormers
+          git config --global --add safe.directory /workspace/PaddleFormers
+          git config user.name "PaddleCI"
+          git config user.email "paddle_ci@example.com"
+          git config pull.rebase false
+          source ../PaddleFleet/.venv/bin/activate
+          pip install -e .
+          '
 
-    - name: Integration test (GLM4.5)
-      if: ${{ matrix.name == 'H20' }}
-      run: |
-        docker exec -t ${{ env.container_name }} /bin/bash -ce '
-        source /root/proxy
-        bash -x PaddleFleet/ci/integration_test/glm45.sh
-        glm45_exit_code=$?
-        if [[ "$glm45_exit_code" != "0" ]]; then
-          echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
-          exit 1
-        else
-          echo -e "\033[32mIntegration test succeeded: GLM4.5.\033[0m"
-        fi
-        '
+      - name: Integration test (GLM4.5)
+        if: ${{ matrix.name == 'H20' }}
+        run: |
+          docker exec -t ${{ env.container_name }} /bin/bash -ce '
+          source /root/proxy
+          bash -x PaddleFleet/ci/integration_test/glm45.sh
+          glm45_exit_code=$?
+          if [[ "$glm45_exit_code" != "0" ]]; then
+            echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
+            exit 1
+          else
+            echo -e "\033[32mIntegration test succeeded: GLM4.5.\033[0m"
+          fi
+          '
 
-    - name: Terminate and delete the container
-      if: ${{ matrix.name == 'H20' && always() }}
-      run: |
-        set +e
-        docker exec -t ${{ env.container_name }} /bin/bash -c 'rm -rf * .[^.]*'
-        docker rm -f ${{ env.container_name }}
+      - name: Terminate and delete the container
+        if: ${{ matrix.name == 'H20' && always() }}
+        run: |
+          set +e
+          docker exec -t ${{ env.container_name }} /bin/bash -c 'rm -rf * .[^.]*'
+          docker rm -f ${{ env.container_name }}
