add analyze log for exit code 250

diff --git a/.github/workflows/Test.yml b/.github/workflows/Test.yml
--- a/.github/workflows/Test.yml
+++ b/.github/workflows/Test.yml
@@ -230,22 +230,15 @@ jobs:
           uv pip install https://paddle-qa.bj.bcebos.com/paddle-pipeline/Develop-GpuAll-LinuxCentos-Gcc11-Cuda129-Cudnn99-Trt105-Py310-Compile/latest/paddlepaddle_gpu-0.0.0-cp310-cp310-linux_x86_64.whl --index-url=https://www.paddlepaddle.org.cn/packages/nightly/cu129/ --force-reinstall
           source .venv/bin/activate
           python -c "import paddle; print(paddle.version.commit)"
-          bash ci/multi-card_test.sh | tee multi_card_test.log
+          bash ci/multi-card_test.sh
           multi_card_exit_code=$?
           ls -a /paddle/coveragedata/
           uv run coverage combine
           uv run coverage xml -o /paddle/coveragedata/coverage.xml
           uv run coverage report -m
           if [[ "$multi_card_exit_code" != "0" ]]; then
-            echo -e "Multi card test failed, try to analyze log."
-            python ci/check_log_for_exitcode.py multi_card_test.log unit
-            find_error_exit_code=$?
-            if [[ "$find_error_exit_code" != "0" ]]; then
-              echo -e "::error:: \033[31mMulti card test failed.\033[0m"
-            else
-              echo -e "\033[32mMulti card test succeeded.\033[0m"
-            fi
-            exit $find_error_exit_code
+            echo -e "::error:: \033[32mMulti card test failed.\033[0m"
+            exit 1
           else
             echo -e "\033[32mMulti card test succeeded.\033[0m"
           fi
@@ -402,26 +395,8 @@ jobs:
           uv run coverage xml -o /workspace/PaddleFleet/coveragedata-single/coverage.xml
           uv run coverage report -m
           if [[ "$glm45_single_card_exit_code" != "0" ]]; then
-            echo -e "Integration test failed: GLM4.5 single-card, try to analyze log."
-            python PaddleFleet/ci/check_log_for_exitcode.py ./glm45_single_card.log integration
-            find_error_exit_code=$?
-            python PaddleFleet/ci/integration_test/check_loss.py --log_file ./glm45_single_card.log --gt_file ./glm45_single_card_gt_loss.txt
-            check_loss_exit_code=$?
-            if [[ "$check_loss_exit_code" == "0" && "$find_error_exit_code" == "0" ]]; then
-              echo -e "\033[32mIntegration test succeeded: GLM4.5 single-card.\033[0m"
-              exit 0
-            else
-              echo -e "::error:: \033[31mIntegration test failed: GLM4.5 single-card.\033[0m"
-              echo "  check_log_for_exitcode exit code: $find_error_exit_code"
-              echo "  check_loss exit code: $check_loss_exit_code"
-              exit 1
-            fi
-            if [[ "$find_error_exit_code" != "0" ]]; then
-              echo -e "::error:: \033[31mIntegration test failed: GLM4.5 single-card.\033[0m"
-            else
-              echo -e "\033[32mIntegration test succeeded: GLM4.5 single-card.\033[0m"
-            fi
-            exit $find_error_exit_code
+            echo -e "::error:: \033[32mIntegration test failed: GLM4.5 single-card\033[0m"
+            exit 1
           else
             echo -e "\033[32mIntegration test succeeded: GLM4.5 single-card.\033[0m"
           fi
@@ -443,20 +418,8 @@ jobs:
           uv run coverage xml -o /workspace/PaddleFleet/coveragedata-qwen/coverage.xml
           uv run coverage report -m
           if [[ "$qwen3_single_card_exit_code" != "0" ]]; then
-            echo -e "Integration test failed: Qwen3-30B-A3B single-card, try to analyze log."
-            python PaddleFleet/ci/check_log_for_exitcode.py ./qwen3_single_card.log integration
-            find_error_exit_code=$?
-            python PaddleFleet/ci/integration_test/check_loss.py --log_file ./qwen3_single_card.log --gt_file ./qwen3_single_card_gt_loss.txt
-            check_loss_exit_code=$?
-            if [[ "$check_loss_exit_code" == "0" && "$find_error_exit_code" == "0" ]]; then
-              echo -e "\033[32mIntegration test succeeded: Qwen3-30B-A3B single-card.\033[0m"
-              exit 0
-            else
-              echo -e "::error:: \033[31mIntegration test failed: Qwen3-30B-A3B single-card.\033[0m"
-              echo "  check_log_for_exitcode exit code: $find_error_exit_code"
-              echo "  check_loss exit code: $check_loss_exit_code"
-              exit 1
-            fi
+            echo -e "::error:: \033[32mIntegration test failed: Qwen3-30B-A3B single-card\033[0m"
+            exit 1
           else
             echo -e "\033[32mIntegration test succeeded: Qwen3-30B-A3B single-card.\033[0m"
           fi
@@ -586,20 +549,8 @@ jobs:
           uv run coverage xml -o /workspace/PaddleFleet/coveragedata-multi/coverage.xml
           uv run coverage report -m
           if [[ "$glm45_exit_code" != "0" ]]; then
-            echo -e "Integration test failed: GLM4.5, try to analyze log."
-            python PaddleFleet/ci/check_log_for_exitcode.py ./glm45.log integration
-            find_error_exit_code=$?
-            python PaddleFleet/ci/integration_test/check_loss.py --log_file ./glm45.log --gt_file ./glm45_multi_card_gt_loss.txt
-            check_loss_exit_code=$?
-            if [ $find_error_exit_code -eq 0 ] && [ $check_loss_exit_code -eq 0 ]; then
-                echo "\033[32mIntegration test succeeded: GLM4.5.\033[0m"
-                exit 0
-            else
-                echo "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
-                echo "  check_log_for_exitcode exit code: $find_error_exit_code"
-                echo "  check_loss exit code: $check_loss_exit_code"
-                exit 1
-            fi
+            echo -e "::error:: \033[32mIntegration test failed: GLM4.5.\033[0m"
+            exit 1
           else
             echo -e "\033[32mIntegration test succeeded: GLM4.5.\033[0m"
           fi
@@ -622,20 +573,8 @@ jobs:
           uv run coverage xml -o /workspace/PaddleFleet/coveragedata-multi-fp8/coverage.xml
           uv run coverage report -m
           if [[ "$glm45_exit_code" != "0" ]]; then
-            echo -e "Integration test failed: GLM4.5, try to analyze log."
-            python PaddleFleet/ci/check_log_for_exitcode.py ./glm45_fp8.log integration
-            find_error_exit_code=$?
-            python PaddleFleet/ci/integration_test/check_loss.py --log_file ./glm45_fp8.log --gt_file ./glm45_multi_cards_fp8_gt_loss.txt
-            check_loss_exit_code=$?
-            if [ $find_error_exit_code -eq 0 ] && [ $check_loss_exit_code -eq 0 ]; then
-                echo "\033[32mIntegration test succeeded: GLM4.5 FP8.\033[0m"
-                exit 0
-            else
-                echo "::error:: \033[31mIntegration test failed: GLM4.5 FP8.\033[0m"
-                echo "  check_log_for_exitcode exit code: $find_error_exit_code"
-                echo "  check_loss exit code: $check_loss_exit_code"
-                exit 1
-            fi
+            echo -e "::error:: \033[32mIntegration test failed: GLM4.5 FP8.\033[0m"
+            exit 1
           else
             echo -e "\033[32mIntegration test succeeded: GLM4.5 FP8.\033[0m"
           fi
@@ -761,15 +700,8 @@ jobs:
           uv run coverage xml -o /workspace/PaddleFleet/coveragedata/coverage.xml
           uv run coverage report -m
           if [[ "$glm45_exit_code" != "0" ]]; then
-            echo -e "Integration test failed: GLM4.5, try to analyze log."
-            python PaddleFleet/ci/check_log_for_exitcode.py ./glm45_a100.log integration
-            find_error_exit_code=$?
-            if [[ "$find_error_exit_code" != "0" ]]; then
-              echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
-            else
-              echo -e "\033[32mIntegration test succeeded: GLM4.5.\033[0m"
-            fi
-            exit $find_error_exit_code
+            echo -e "::error:: \033[32mIntegration test failed: GLM4.5.\033[0m"
+            exit 1
           else
             echo -e "\033[32mIntegration test succeeded: GLM4.5.\033[0m"
           fi
