Revert "[CI]find error for log (#200)"
This reverts commit feb8e9351c8681d1fb210d4902ffc6a24b6db4d7.

diff --git a/.github/workflows/Test.yml b/.github/workflows/Test.yml
--- a/.github/workflows/Test.yml
+++ b/.github/workflows/Test.yml
@@ -230,22 +230,16 @@ jobs:
           uv pip install https://paddle-qa.bj.bcebos.com/paddle-pipeline/Develop-GpuAll-LinuxCentos-Gcc11-Cuda129-Cudnn99-Trt105-Py310-Compile/latest/paddlepaddle_gpu-0.0.0-cp310-cp310-linux_x86_64.whl --index-url=https://www.paddlepaddle.org.cn/packages/nightly/cu129/ --force-reinstall
           source .venv/bin/activate
           python -c "import paddle; print(paddle.version.commit)"
-          bash ci/multi-card_test.sh | tee multi_card_test.log
+          bash ci/multi-card_test.sh
           multi_card_exit_code=$?
           ls -a /paddle/coveragedata/
           uv run coverage combine
           uv run coverage xml -o /paddle/coveragedata/coverage.xml
           uv run coverage report -m
+
           if [[ "$multi_card_exit_code" != "0" ]]; then
-            echo -e "Multi card test failed, try to analyze log."
-            python ci/check_log_for_exitcode.py multi_card_test.log unit
-            find_error_exit_code=$?
-            if [[ "$find_error_exit_code" != "0" ]]; then
-              echo -e "::error:: \033[31mMulti card test failed.\033[0m"
-            else
-              echo -e "\033[32mMulti card test succeeded.\033[0m"
-            fi
-            exit $find_error_exit_code
+            echo -e "::error:: \033[31mMulti card test failed.\033[0m"
+            exit 1
           else
             echo -e "\033[32mMulti card test succeeded.\033[0m"
           fi
@@ -394,7 +388,7 @@ jobs:
           mkdir -p /workspace/PaddleFleet/coveragedata-single
           export COVERAGE_FILE=/workspace/PaddleFleet/coveragedata-single/.coverage
           export COVERAGE_RCFILE=/workspace/PaddleFleet/ci/.coveragerc
-          bash -x PaddleFleet/ci/integration_test/glm45_single_card.sh | tee glm45_single_card.log
+          bash -x PaddleFleet/ci/integration_test/glm45_single_card.sh
           glm45_single_card_exit_code=$?
           ls -a /workspace/PaddleFleet/coveragedata-single
           source /workspace/PaddleFleet/.venv/bin/activate
@@ -402,15 +396,8 @@ jobs:
           uv run coverage xml -o /workspace/PaddleFleet/coveragedata-single/coverage.xml
           uv run coverage report -m
           if [[ "$glm45_single_card_exit_code" != "0" ]]; then
-            echo -e "Integration test failed: GLM4.5 single-card, try to analyze log."
-            python PaddleFleet/ci/check_log_for_exitcode.py glm45_single_card.log integration true
-            find_error_exit_code=$?
-            if [[ "$find_error_exit_code" != "0" ]]; then
-              echo -e "::error:: \033[31mIntegration test failed: GLM4.5 single-card.\033[0m"
-            else
-              echo -e "\033[32mIntegration test succeeded: GLM4.5 single-card.\033[0m"
-            fi
-            exit $find_error_exit_code
+            echo -e "::error:: \033[31mIntegration test failed: GLM4.5 single-card.\033[0m"
+            exit 1
           else
             echo -e "\033[32mIntegration test succeeded: GLM4.5 single-card.\033[0m"
           fi
@@ -424,7 +411,7 @@ jobs:
           mkdir -p /workspace/PaddleFleet/coveragedata-qwen
           export COVERAGE_FILE=/workspace/PaddleFleet/coveragedata-qwen/.coverage
           export COVERAGE_RCFILE=/workspace/PaddleFleet/ci/.coveragerc
-          bash -x PaddleFleet/ci/integration_test/qwen3_single_card.sh | tee qwen3_single_card.log
+          bash -x PaddleFleet/ci/integration_test/qwen3_single_card.sh
           qwen3_single_card_exit_code=$?
           ls -a /workspace/PaddleFleet/coveragedata-qwen
           source /workspace/PaddleFleet/.venv/bin/activate
@@ -432,15 +419,8 @@ jobs:
           uv run coverage xml -o /workspace/PaddleFleet/coveragedata-qwen/coverage.xml
           uv run coverage report -m
           if [[ "$qwen3_single_card_exit_code" != "0" ]]; then
-            echo -e "Integration test failed: Qwen3-30B-A3B single-card, try to analyze log."
-            python PaddleFleet/ci/check_log_for_exitcode.py qwen3_single_card.log integration true
-            find_error_exit_code=$?
-            if [[ "$find_error_exit_code" != "0" ]]; then
-              echo -e "::error:: \033[31mIntegration test failed: Qwen3-30B-A3B single-card.\033[0m"
-            else
-              echo -e "\033[32mIntegration test succeeded: Qwen3-30B-A3B single-card.\033[0m"
-            fi
-            exit $find_error_exit_code
+            echo -e "::error:: \033[31mIntegration test failed: Qwen3-30B-A3B single-card.\033[0m"
+            exit 1
           else
             echo -e "\033[32mIntegration test succeeded: Qwen3-30B-A3B single-card.\033[0m"
           fi
@@ -561,7 +541,7 @@ jobs:
           mkdir -p /workspace/PaddleFleet/coveragedata-multi
           export COVERAGE_FILE=/workspace/PaddleFleet/coveragedata-multi/.coverage
           export COVERAGE_RCFILE=/workspace/PaddleFleet/ci/.coveragerc
-          bash -x PaddleFleet/ci/integration_test/glm45.sh | tee glm45.log
+          bash -x PaddleFleet/ci/integration_test/glm45.sh
           glm45_exit_code=$?
           ls -a /workspace/PaddleFleet/coveragedata-multi
           source /workspace/PaddleFleet/.venv/bin/activate
@@ -570,15 +550,8 @@ jobs:
           uv run coverage xml -o /workspace/PaddleFleet/coveragedata-multi/coverage.xml
           uv run coverage report -m
           if [[ "$glm45_exit_code" != "0" ]]; then
-            echo -e "Integration test failed: GLM4.5, try to analyze log."
-            python PaddleFleet/ci/check_log_for_exitcode.py glm45.log integration true
-            find_error_exit_code=$?
-            if [[ "$find_error_exit_code" != "0" ]]; then
-              echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
-            else
-              echo -e "\033[32mIntegration test succeeded: GLM4.5.\033[0m"
-            fi
-            exit $find_error_exit_code
+            echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
+            exit 1
           else
             echo -e "\033[32mIntegration test succeeded: GLM4.5.\033[0m"
           fi
@@ -592,7 +565,7 @@ jobs:
           mkdir -p /workspace/PaddleFleet/coveragedata-multi-fp8
           export COVERAGE_FILE=/workspace/PaddleFleet/coveragedata-multi-fp8/.coverage
           export COVERAGE_RCFILE=/workspace/PaddleFleet/ci/.coveragerc
-          bash -x PaddleFleet/ci/integration_test/glm45_fp8.sh | tee glm45_fp8.log
+          bash -x PaddleFleet/ci/integration_test/glm45_fp8.sh
           glm45_exit_code=$?
           ls -a /workspace/PaddleFleet/coveragedata-multi-fp8
           source /workspace/PaddleFleet/.venv/bin/activate
@@ -601,15 +574,8 @@ jobs:
           uv run coverage xml -o /workspace/PaddleFleet/coveragedata-multi-fp8/coverage.xml
           uv run coverage report -m
           if [[ "$glm45_exit_code" != "0" ]]; then
-            echo -e "Integration test failed: GLM4.5, try to analyze log."
-            python PaddleFleet/ci/check_log_for_exitcode.py glm45_fp8.log integration
-            find_error_exit_code=$?
-            if [[ "$find_error_exit_code" != "0" ]]; then
-              echo -e "::error:: \033[31mIntegration test failed: GLM4.5 FP8.\033[0m"
-            else
-              echo -e "\033[32mIntegration test succeeded: GLM4.5.\033[0m"
-            fi
-            exit $find_error_exit_code
+            echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
+            exit 1
           else
             echo -e "\033[32mIntegration test succeeded: GLM4.5.\033[0m"
           fi
@@ -727,7 +693,7 @@ jobs:
           source /root/proxy
           export COVERAGE_FILE=/workspace/PaddleFleet/coveragedata/.coverage
           export COVERAGE_RCFILE=/workspace/PaddleFleet/ci/.coveragerc
-          bash -x PaddleFleet/ci/integration_test/glm45_a100.sh | tee glm45_a100.log
+          bash -x PaddleFleet/ci/integration_test/glm45_a100.sh
           glm45_exit_code=$?
           ls -a /workspace/PaddleFleet/coveragedata
           source /workspace/PaddleFleet/.venv/bin/activate
@@ -735,15 +701,8 @@ jobs:
           uv run coverage xml -o /workspace/PaddleFleet/coveragedata/coverage.xml
           uv run coverage report -m
           if [[ "$glm45_exit_code" != "0" ]]; then
-            echo -e "Integration test failed: GLM4.5, try to analyze log."
-            python PaddleFleet/ci/check_log_for_exitcode.py glm45_a100.log integration false
-            find_error_exit_code=$?
-            if [[ "$find_error_exit_code" != "0" ]]; then
-              echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
-            else
-              echo -e "\033[32mLog analysis did not find specific errors.\033[0m"
-            fi
-            exit $find_error_exit_code
+            echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
+            exit 1
           else
             echo -e "\033[32mIntegration test succeeded: GLM4.5.\033[0m"
           fi
