test

diff --git a/.github/workflows/Test.yml b/.github/workflows/Test.yml
--- a/.github/workflows/Test.yml
+++ b/.github/workflows/Test.yml
@@ -160,7 +160,7 @@ jobs:
     needs: check-bypass
     if: ${{ needs.check-bypass.outputs.can-skip != 'true' }}
     runs-on:
-      group: Fleet-H-multi-card
+      group: test-h
     env:
       PIP_CACHE_DIR: /root/.cache/pip
       TASK: paddlefleet-CI-${{ github.event.pull_request.number }}-multi-card_test
@@ -737,27 +737,27 @@ jobs:
           fi
           '
 
-      - name: GLM4.5 sft+lora
-        run: |
-          docker exec -t ${{ env.container_name }} /bin/bash -ce '
-          source /root/proxy
-          source /root/proxy
-          export COVERAGE_FILE=/workspace/PaddleFleet/coveragedata-sft/.coverage
-          export COVERAGE_RCFILE=/workspace/PaddleFleet/ci/.coveragerc
-          bash -x PaddleFleet/ci/integration_test/glm45_sft_a100.sh
-          glm45_exit_code=$?
-          ls -a /workspace/PaddleFleet/coveragedata-sft
-          source /workspace/PaddleFleet/.venv/bin/activate
-          uv run coverage combine
-          uv run coverage xml -o /workspace/PaddleFleet/coveragedata-sft/coverage.xml
-          uv run coverage report -m
-          if [[ "$glm45_exit_code" != "0" ]]; then
-            echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
-            exit 1
-          else
-            echo -e "\033[32mIntegration test succeeded: GLM4.5.\033[0m"
-          fi
-          '
+      # - name: GLM4.5 sft+lora
+      #   run: |
+      #     docker exec -t ${{ env.container_name }} /bin/bash -ce '
+      #     source /root/proxy
+      #     source /root/proxy
+      #     export COVERAGE_FILE=/workspace/PaddleFleet/coveragedata-sft/.coverage
+      #     export COVERAGE_RCFILE=/workspace/PaddleFleet/ci/.coveragerc
+      #     bash -x PaddleFleet/ci/integration_test/glm45_sft_a100.sh
+      #     glm45_exit_code=$?
+      #     ls -a /workspace/PaddleFleet/coveragedata-sft
+      #     source /workspace/PaddleFleet/.venv/bin/activate
+      #     uv run coverage combine
+      #     uv run coverage xml -o /workspace/PaddleFleet/coveragedata-sft/coverage.xml
+      #     uv run coverage report -m
+      #     if [[ "$glm45_exit_code" != "0" ]]; then
+      #       echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
+      #       exit 1
+      #     else
+      #       echo -e "\033[32mIntegration test succeeded: GLM4.5.\033[0m"
+      #     fi
+      #     '
 
       - name: A100 Coverage Upload to BOS
         run: |
@@ -767,10 +767,10 @@ jobs:
             -O bos_tools.py
           push_file=$(realpath bos_tools.py)
           cp /workspace/PaddleFleet/coveragedata-pt/coverage.xml coverage-a-pt.xml
-          cp /workspace/PaddleFleet/coveragedata-sft/coverage.xml coverage-a-sft.xml
+          # cp /workspace/PaddleFleet/coveragedata-sft/coverage.xml coverage-a-sft.xml
           target_path="paddle-github-action/${GITHUB_REPO_NAME}/pull/${PR_ID}/${GITHUB_SHA}/a100"
           uv run ${push_file} coverage-a-pt.xml ${target_path}
-          uv run ${push_file} coverage-a-sft.xml ${target_path}
+          # uv run ${push_file} coverage-a-sft.xml ${target_path}
           '
 
       - name: Terminate and delete the container
@@ -810,8 +810,6 @@ jobs:
           wget "${h20_multi_pt_cov_file_url}" -O h20_multi_pt_coverage.xml --no-proxy
           h20_multi_sft_cov_file_url="https://paddle-github-action.bj.bcebos.com/${GITHUB_REPO_NAME}/pull/${PR_ID}/${COMMIT_ID}/h20-multi/coverage-multi-sft.xml"
           wget "${h20_multi_sft_cov_file_url}" -O h20_multi_sft_coverage.xml --no-proxy
-          h20_multi_lora_cov_file_url="https://paddle-github-action.bj.bcebos.com/${GITHUB_REPO_NAME}/pull/${PR_ID}/${COMMIT_ID}/h20-multi/coverage-multi-sft.xml"
-          wget "${h20_multi_lora_cov_file_url}" -O h20_multi_lora_coverage.xml --no-proxy
           h20_multi_fp8_cov_file_url="https://paddle-github-action.bj.bcebos.com/${GITHUB_REPO_NAME}/pull/${PR_ID}/${COMMIT_ID}/h20-multi-fp8/coverage-multi-fp8.xml"
           wget "${h20_multi_fp8_cov_file_url}" -O h20_multi_fp8_coverage.xml --no-proxy
           h20_single_cov_file_url="https://paddle-github-action.bj.bcebos.com/${GITHUB_REPO_NAME}/pull/${PR_ID}/${COMMIT_ID}/h20-single/coverage-single.xml"
@@ -820,36 +818,30 @@ jobs:
           wget "${h20_qwen_cov_file_url}" -O h20_qwen_coverage.xml --no-proxy
           a100_pt_cov_file_url="https://paddle-github-action.bj.bcebos.com/${GITHUB_REPO_NAME}/pull/${PR_ID}/${COMMIT_ID}/a100/coverage-a-pt.xml"
           wget "${a100_cov_file_url}" -O a100_pt_coverage.xml --no-proxy
-          a100_sft_cov_file_url="https://paddle-github-action.bj.bcebos.com/${GITHUB_REPO_NAME}/pull/${PR_ID}/${COMMIT_ID}/a100/coverage-a-sft.xml"
-          wget "${a100_cov_file_url}" -O a100_sft_coverage.xml --no-proxy
-          a100_lora_cov_file_url="https://paddle-github-action.bj.bcebos.com/${GITHUB_REPO_NAME}/pull/${PR_ID}/${COMMIT_ID}/a100/coverage-a-lora.xml"
-          wget "${a100_cov_file_url}" -O a100_lora_coverage.xml --no-proxy
+          # a100_sft_cov_file_url="https://paddle-github-action.bj.bcebos.com/${GITHUB_REPO_NAME}/pull/${PR_ID}/${COMMIT_ID}/a100/coverage-a-sft.xml"
+          # wget "${a100_cov_file_url}" -O a100_sft_coverage.xml --no-proxy
           sed -i 's|<source>/paddle/paddlefleet</source>|<source>paddlefleet</source>|' multi_coverage.xml
           sed -i 's|<source>/paddle/paddlefleet</source>|<source>paddlefleet</source>|' single_coverage.xml
           sed -i 's|<source>/paddle/paddlefleet</source>|<source>paddlefleet</source>|' h20_multi_pt_coverage.xml
           sed -i 's|<source>/paddle/paddlefleet</source>|<source>paddlefleet</source>|' h20_multi_sft_coverage.xml
-          sed -i 's|<source>/paddle/paddlefleet</source>|<source>paddlefleet</source>|' h20_multi_lora_coverage.xml
           sed -i 's|<source>/paddle/paddlefleet</source>|<source>paddlefleet</source>|' h20_multi_fp8_coverage.xml
           sed -i 's|<source>/paddle/paddlefleet</source>|<source>paddlefleet</source>|' h20_single_coverage.xml
           sed -i 's|<source>/paddle/paddlefleet</source>|<source>paddlefleet</source>|' h20_qwen_coverage.xml
           sed -i 's|<source>/paddle/paddlefleet</source>|<source>paddlefleet</source>|' a100_pt_coverage.xml
-          sed -i 's|<source>/paddle/paddlefleet</source>|<source>paddlefleet</source>|' a100_sft_coverage.xml
-          sed -i 's|<source>/paddle/paddlefleet</source>|<source>paddlefleet</source>|' a100_lora_coverage.xml
+          # sed -i 's|<source>/paddle/paddlefleet</source>|<source>paddlefleet</source>|' a100_sft_coverage.xml
           git diff origin/${{ github.event.pull_request.base.ref }}..HEAD --unified=0 > diff.txt
           python -m pip install diff-cover
           COVERAGE_EXIT_CODE=0
-          diff-cover multi_coverage.xml single_coverage.xml h20_multi_pt_coverage.xml h20_multi_sft_coverage.xml h20_multi_lora_coverage.xml h20_multi_fp8_coverage.xml \
-          h20_single_coverage.xml h20_qwen_coverage.xml a100_pt_coverage.xml a100_sft_coverage.xml a100_lora_coverage.xml --diff-file=diff.txt --fail-under=90 || COVERAGE_EXIT_CODE=9
+          diff-cover multi_coverage.xml single_coverage.xml h20_multi_pt_coverage.xml h20_multi_sft_coverage.xml h20_multi_fp8_coverage.xml \
+          h20_single_coverage.xml h20_qwen_coverage.xml a100_pt_coverage.xml --diff-file=diff.txt --fail-under=90 || COVERAGE_EXIT_CODE=9
           python ci/filter_coverage.py multi_coverage.xml diff.txt
           python ci/filter_coverage.py single_coverage.xml diff.txt
           python ci/filter_coverage.py h20_multi_pt_coverage.xml diff.txt
           python ci/filter_coverage.py h20_multi_sft_coverage.xml diff.txt
-          python ci/filter_coverage.py h20_multi_lora_coverage.xml diff.txt
           python ci/filter_coverage.py h20_single_coverage.xml diff.txt
           python ci/filter_coverage.py h20_qwen_coverage.xml diff.txt
           python ci/filter_coverage.py a100_pt_coverage.xml diff.txt
-          python ci/filter_coverage.py a100_sft_coverage.xml diff.txt
-          python ci/filter_coverage.py a100_lora_coverage.xml diff.txt
+          # python ci/filter_coverage.py a100_sft_coverage.xml diff.txt
           python ci/filter_coverage.py h20_multi_fp8_coverage.xml diff.txt
           exit ${COVERAGE_EXIT_CODE}
 
@@ -864,12 +856,9 @@ jobs:
             "single_coverage.xml"
             "h20_multi_pt_coverage.xml"
             "h20_multi_sft_coverage.xml"
-            "h20_multi_lora_coverage.xml"
             "h20_single_coverage.xml"
             "h20_qwen_coverage.xml"
             "a100_pt_coverage.xml"
-            "a100_sft_coverage.xml"
-            "a100_lora_coverage.xml"
             "h20_multi_fp8_coverage.xml"
           )
 
@@ -1011,7 +1000,7 @@ jobs:
         if: always()
         uses: codecov/codecov-action@v4
         with:
-          files: ./multi_coverage.xml,./single_coverage.xml,./h20_multi_pt_coverage.xml,./h20_multi_sft_coverage.xml,./h20_multi_lora_coverage.xml,./h20_multi_fp8_coverage.xml,./h20_single_coverage.xml,./h20_qwen_coverage.xml,./a100_pt_coverage.xml,./a100_sft_coverage.xml,./a100_lora_coverage.xml
+          files: ./multi_coverage.xml,./single_coverage.xml,./h20_multi_pt_coverage.xml,./h20_multi_sft_coverage.xml,./h20_multi_fp8_coverage.xml,./h20_single_coverage.xml,./h20_qwen_coverage.xml,./a100_pt_coverage.xml
           flags: coverage_combine
           name: "${{ env.TASK }}-${{ github.run_id }}"
           fail_ci_if_error: true
