add sft+lora

diff --git a/.github/workflows/Test.yml b/.github/workflows/Test.yml
--- a/.github/workflows/Test.yml
+++ b/.github/workflows/Test.yml
@@ -738,27 +738,27 @@ jobs:
           fi
           '
 
-      - name: GLM4.5 sft+lora
-        run: |
-          docker exec -t ${{ env.container_name }} /bin/bash -ce '
-          source /root/proxy
-          source /root/proxy
-          export COVERAGE_FILE=/workspace/PaddleFleet/coveragedata-sft/.coverage
-          export COVERAGE_RCFILE=/workspace/PaddleFleet/ci/.coveragerc
-          bash -x PaddleFleet/ci/integration_test/glm45_sft_a100.sh
-          glm45_exit_code=$?
-          ls -a /workspace/PaddleFleet/coveragedata-sft
-          source /workspace/PaddleFleet/.venv/bin/activate
-          uv run coverage combine
-          uv run coverage xml -o /workspace/PaddleFleet/coveragedata-sft/coverage.xml
-          uv run coverage report -m
-          if [[ "$glm45_exit_code" != "0" ]]; then
-            echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
-            exit 1
-          else
-            echo -e "\033[32mIntegration test succeeded: GLM4.5.\033[0m"
-          fi
-          '
+      # - name: GLM4.5 sft+lora
+      #   run: |
+      #     docker exec -t ${{ env.container_name }} /bin/bash -ce '
+      #     source /root/proxy
+      #     source /root/proxy
+      #     export COVERAGE_FILE=/workspace/PaddleFleet/coveragedata-sft/.coverage
+      #     export COVERAGE_RCFILE=/workspace/PaddleFleet/ci/.coveragerc
+      #     bash -x PaddleFleet/ci/integration_test/glm45_sft_a100.sh
+      #     glm45_exit_code=$?
+      #     ls -a /workspace/PaddleFleet/coveragedata-sft
+      #     source /workspace/PaddleFleet/.venv/bin/activate
+      #     uv run coverage combine
+      #     uv run coverage xml -o /workspace/PaddleFleet/coveragedata-sft/coverage.xml
+      #     uv run coverage report -m
+      #     if [[ "$glm45_exit_code" != "0" ]]; then
+      #       echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
+      #       exit 1
+      #     else
+      #       echo -e "\033[32mIntegration test succeeded: GLM4.5.\033[0m"
+      #     fi
+      #     '
 
       - name: A100 Coverage Upload to BOS
         run: |
