update

diff --git a/.github/workflows/Test.yml b/.github/workflows/Test.yml
--- a/.github/workflows/Test.yml
+++ b/.github/workflows/Test.yml
@@ -37,125 +37,125 @@ jobs:
     secrets:
       github-token: ${{ secrets.GITHUB_TOKEN }}
 
-  single_card_test:
-    name: Single card test
-    needs: check-bypass
-    if: ${{ needs.check-bypass.outputs.can-skip != 'true' }}
-    runs-on:
-      group: BD_BJ-V100
-    env:
-      PIP_CACHE_DIR: /root/.cache/pip
-    steps:
-      - name: Check docker image and run container
-        run: |
-          container_name=${TASK}-$(date +%Y%m%d-%H%M%S)
-          echo "container_name=${container_name}" >> ${{ github.env }}
-          docker pull $docker_image
-          docker run -d -t --gpus all --name ${container_name} \
-            -v "/dev/shm:/dev/shm"  \
-            -v "/home/data/cfs:/home/data/cfs" \
-            -v "/home/data/cfs/.cache:/root/.cache" \
-            -v ${{ github.workspace }}/../../..:${{ github.workspace }}/../../.. \
-            -v ${{ github.workspace }}/../../../proxy:/root/proxy \
-            -v ${{ github.workspace }}:/paddle \
-            -e BRANCH \
-            -e PR_ID \
-            -e COMMIT_ID \
-            -e work_dir \
-            -e PADDLE_ROOT \
-            -e ci_scripts \
-            -e CACHE_DIR \
-            -e no_proxy \
-            -e CI_name \
-            -e PIP_CACHE_DIR \
-            -e GITHUB_SHA="${{ github.event.pull_request.head.sha }}" \
-            -e GITHUB_HEAD_REF="${{ github.head_ref }}" \
-            -e GITHUB_BASE_SHA="${{ github.event.pull_request.base.sha }}" \
-            -e GITHUB_REPO_NAME="${{ github.repository }}" \
-            -e GITHUB_EVENT_PULL_REQUEST_NUMBER="${{ github.event.pull_request.number }}" \
-            -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
-            -e GITHUB_RUN_ID="${{ github.run_id }}" \
-            -w /paddle --network host ${docker_image}
+  # single_card_test:
+  #   name: Single card test
+  #   needs: check-bypass
+  #   if: ${{ needs.check-bypass.outputs.can-skip != 'true' }}
+  #   runs-on:
+  #     group: BD_BJ-V100
+  #   env:
+  #     PIP_CACHE_DIR: /root/.cache/pip
+  #   steps:
+  #     - name: Check docker image and run container
+  #       run: |
+  #         container_name=${TASK}-$(date +%Y%m%d-%H%M%S)
+  #         echo "container_name=${container_name}" >> ${{ github.env }}
+  #         docker pull $docker_image
+  #         docker run -d -t --gpus all --name ${container_name} \
+  #           -v "/dev/shm:/dev/shm"  \
+  #           -v "/home/data/cfs:/home/data/cfs" \
+  #           -v "/home/data/cfs/.cache:/root/.cache" \
+  #           -v ${{ github.workspace }}/../../..:${{ github.workspace }}/../../.. \
+  #           -v ${{ github.workspace }}/../../../proxy:/root/proxy \
+  #           -v ${{ github.workspace }}:/paddle \
+  #           -e BRANCH \
+  #           -e PR_ID \
+  #           -e COMMIT_ID \
+  #           -e work_dir \
+  #           -e PADDLE_ROOT \
+  #           -e ci_scripts \
+  #           -e CACHE_DIR \
+  #           -e no_proxy \
+  #           -e CI_name \
+  #           -e PIP_CACHE_DIR \
+  #           -e GITHUB_SHA="${{ github.event.pull_request.head.sha }}" \
+  #           -e GITHUB_HEAD_REF="${{ github.head_ref }}" \
+  #           -e GITHUB_BASE_SHA="${{ github.event.pull_request.base.sha }}" \
+  #           -e GITHUB_REPO_NAME="${{ github.repository }}" \
+  #           -e GITHUB_EVENT_PULL_REQUEST_NUMBER="${{ github.event.pull_request.number }}" \
+  #           -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
+  #           -e GITHUB_RUN_ID="${{ github.run_id }}" \
+  #           -w /paddle --network host ${docker_image}
 
-      - name: Clone PaddleFleet
-        run: |
-          docker exec -t ${{ env.container_name }} /bin/bash -c '
-          rm -rf * .[^.]*
-          set -e
-          source /root/proxy
-          git clone https://github.com/PaddlePaddle/PaddleFleet.git .
-          git config --global --add safe.directory /paddle
-          git config user.name "PaddleCI"
-          git config user.email "paddle_ci@example.com"
-          git config pull.rebase false
-          git pull --no-edit origin pull/${PR_ID}/head
-          mkdir -p /root/.cache/pip
-          pip cache dir
-          echo "Install uv"
-          curl -LsSf https://astral.sh/uv/install.sh | sh
-          source $HOME/.local/bin/env
-          echo "uv sync"
-          uv sync --group ci> /dev/null 2>&1
-          '
+  #     - name: Clone PaddleFleet
+  #       run: |
+  #         docker exec -t ${{ env.container_name }} /bin/bash -c '
+  #         rm -rf * .[^.]*
+  #         set -e
+  #         source /root/proxy
+  #         git clone https://github.com/PaddlePaddle/PaddleFleet.git .
+  #         git config --global --add safe.directory /paddle
+  #         git config user.name "PaddleCI"
+  #         git config user.email "paddle_ci@example.com"
+  #         git config pull.rebase false
+  #         git pull --no-edit origin pull/${PR_ID}/head
+  #         mkdir -p /root/.cache/pip
+  #         pip cache dir
+  #         echo "Install uv"
+  #         curl -LsSf https://astral.sh/uv/install.sh | sh
+  #         source $HOME/.local/bin/env
+  #         echo "uv sync"
+  #         uv sync --group ci> /dev/null 2>&1
+  #         '
 
-      - name: Single card test
-        if: steps.check-bypass.outputs.can-skip != 'true'
-        run: |
-          docker exec -t ${{ env.container_name }} /bin/bash -xc '
-          source $HOME/.local/bin/env
-          pwd
-          export COVERAGE_FILE=/paddle/coveragedata/.coverage
-          export COVERAGE_RCFILE=/paddle/ci/.coveragerc
-          export WITH_COVERAGE=ON
+  #     - name: Single card test
+  #       if: steps.check-bypass.outputs.can-skip != 'true'
+  #       run: |
+  #         docker exec -t ${{ env.container_name }} /bin/bash -xc '
+  #         source $HOME/.local/bin/env
+  #         pwd
+  #         export COVERAGE_FILE=/paddle/coveragedata/.coverage
+  #         export COVERAGE_RCFILE=/paddle/ci/.coveragerc
+  #         export WITH_COVERAGE=ON
   
-          bash ci/single_card_test.sh
-          single_card_exit_code=$?
-          ls -a /paddle/coveragedata/
-          uv run coverage combine
-          uv run coverage report -m
-          uv run coverage xml -o /paddle/coveragedata/coverage.xml
-          if [[ "$single_card_exit_code" != "0" ]]; then
-            echo -e "::error:: \033[31mSingle card test failed.\033[0m"
-            exit 1
-          else
-            echo -e "\033[32mSingle card test succeeded.\033[0m"
-          fi
-          '
-      # - name: Upload coverage to Codecov
-      #   if: always()
-      #   uses: codecov/codecov-action@v4
-      #   with:
-      #     files: ${{ github.workspace }}/coveragedata/coverage.xml
-      #     flags: single-card
-      #     name: "${{ env.TASK }}-${{ github.run_id }}"
-      #     fail_ci_if_error: true
-      #     verbose: true
+  #         bash ci/single_card_test.sh
+  #         single_card_exit_code=$?
+  #         ls -a /paddle/coveragedata/
+  #         uv run coverage combine
+  #         uv run coverage report -m
+  #         uv run coverage xml -o /paddle/coveragedata/coverage.xml
+  #         if [[ "$single_card_exit_code" != "0" ]]; then
+  #           echo -e "::error:: \033[31mSingle card test failed.\033[0m"
+  #           exit 1
+  #         else
+  #           echo -e "\033[32mSingle card test succeeded.\033[0m"
+  #         fi
+  #         '
+  #     # - name: Upload coverage to Codecov
+  #     #   if: always()
+  #     #   uses: codecov/codecov-action@v4
+  #     #   with:
+  #     #     files: ${{ github.workspace }}/coveragedata/coverage.xml
+  #     #     flags: single-card
+  #     #     name: "${{ env.TASK }}-${{ github.run_id }}"
+  #     #     fail_ci_if_error: true
+  #     #     verbose: true
 
-      - name: Single-card Coverage Upload
-        if: steps.check-bypass.outputs.can-skip != 'true'
-        run: |
-          docker exec -t ${{ env.container_name }} /bin/bash -xc '
-          source $HOME/.local/bin/env
-          export COVERAGE_FILE=/paddle/coveragedata/.coverage
-          export COVERAGE_RCFILE=/paddle/ci/.coveragerc
-          export WITH_COVERAGE=ON
-          uv run codecov-cli detect
-          uv run codecov-cli upload-process \
-            --file /paddle/coveragedata/coverage.xml \
-            --slug ${GITHUB_REPO_NAME} \
-            --commit-sha ${GITHUB_SHA} \
-            --parent-sha ${GITHUB_BASE_SHA} \
-            -e GITHUB_EVENT_NAME="${{ github.event_name }}" \
-            --pr "${GITHUB_EVENT_PULL_REQUEST_NUMBER}" \
-            --flag single-card
-          '
+  #     - name: Single-card Coverage Upload
+  #       if: steps.check-bypass.outputs.can-skip != 'true'
+  #       run: |
+  #         docker exec -t ${{ env.container_name }} /bin/bash -xc '
+  #         source $HOME/.local/bin/env
+  #         export COVERAGE_FILE=/paddle/coveragedata/.coverage
+  #         export COVERAGE_RCFILE=/paddle/ci/.coveragerc
+  #         export WITH_COVERAGE=ON
+  #         uv run codecov-cli detect
+  #         uv run codecov-cli upload-process \
+  #           --file /paddle/coveragedata/coverage.xml \
+  #           --slug ${GITHUB_REPO_NAME} \
+  #           --commit-sha ${GITHUB_SHA} \
+  #           --parent-sha ${GITHUB_BASE_SHA} \
+  #           -e GITHUB_EVENT_NAME="${{ github.event_name }}" \
+  #           --pr "${GITHUB_EVENT_PULL_REQUEST_NUMBER}" \
+  #           --flag single-card
+  #         '
 
-      - name: Terminate and delete the container
-        if: ${{ steps.check-bypass.outputs.can-skip != 'true' && always() }}
-        run: |
-          set +e
-          docker exec -t ${{ env.container_name }} /bin/bash -c 'rm -rf * .[^.]*'
-          docker rm -f ${{ env.container_name }}
+  #     - name: Terminate and delete the container
+  #       if: ${{ steps.check-bypass.outputs.can-skip != 'true' && always() }}
+  #       run: |
+  #         set +e
+  #         docker exec -t ${{ env.container_name }} /bin/bash -c 'rm -rf * .[^.]*'
+  #         docker rm -f ${{ env.container_name }}
 
   multi-card_test:
     name: Multi-card test
@@ -262,21 +262,15 @@ jobs:
       - name: Multi-card Coverage Upload
         if: steps.check-bypass.outputs.can-skip != 'true'
         run: |
-          docker exec -t ${{ env.container_name }} /bin/bash -xc '
-          source $HOME/.local/bin/env
-          export COVERAGE_FILE=/paddle/coveragedata/.coverage
-          export COVERAGE_RCFILE=/paddle/ci/.coveragerc
-          export WITH_COVERAGE=ON
+          export PATH=/home/paddle-1/miniconda3/bin:${PATH}
+          python --version
+          python -m pip install codecov-cli
 
-          uv run codecov-cli detect
-          uv run codecov-cli upload-process \
-            --file /paddle/coveragedata/coverage.xml \
-            --slug ${GITHUB_REPO_NAME} \
-            --commit-sha ${GITHUB_SHA} \
-            --parent-sha ${GITHUB_BASE_SHA} \
-            --pr "${GITHUB_EVENT_PULL_REQUEST_NUMBER}" \
+          export COVERAGE_FILE=${{ github.workspace }}/coveragedata/.coverage
+          export COVERAGE_RCFILE=${{ github.workspace }}/ci/.coveragerc
+          codecov-cli upload-process \
+            --file ${{ github.workspace }}/coveragedata/coverage.xml \
             --flag multi-card
-          '
 
       - name: Terminate and delete the container
         if: ${{ steps.check-bypass.outputs.can-skip != 'true' && always() }}
