add disable test

diff --git a/.github/workflows/Test.yml b/.github/workflows/Test.yml
--- a/.github/workflows/Test.yml
+++ b/.github/workflows/Test.yml
@@ -37,15 +37,14 @@ jobs:
     secrets:
       github-token: ${{ secrets.GITHUB_TOKEN }}
 
-  test:
-    name: Test
+  single_card_test:
+    name: Single card test
     needs: check-bypass
     if: ${{ needs.check-bypass.outputs.can-skip != 'true' }}
     runs-on:
-      group: CI-H
+      group: BD_BJ-V100
     env:
       PIP_CACHE_DIR: /root/.cache/pip
-
     steps:
       - name: Check docker image and run container
         run: |
@@ -95,7 +94,69 @@ jobs:
           docker exec -t ${{ env.container_name }} /bin/bash -c '
           bash ci/single_card_test.sh
           single_card_exit_code=$?
-          echo "single_card_exit_code=$single_card_exit_code" >> ${{ github.env }}
+          if [[ "$single_card_exit_code" != "0" ]]; then
+            echo -e "::error:: \033[31mSingle card test failed.\033[0m"
+            exit 1
+          else
+            echo -e "\033[32mSingle card test succeeded.\033[0m"
+          fi
+          '
+
+      - name: Terminate and delete the container
+        if: ${{ steps.check-bypass.outputs.can-skip != 'true' && always() }}
+        run: |
+          set +e
+          docker exec -t ${{ env.container_name }} /bin/bash -c 'rm -rf * .[^.]*'
+          docker rm -f ${{ env.container_name }}
+
+  multi-card_test:
+    name: Multi-card test
+    needs: check-bypass
+    if: ${{ needs.check-bypass.outputs.can-skip != 'true' }}
+    runs-on:
+      group: CI-H
+    env:
+      PIP_CACHE_DIR: /root/.cache/pip
+    steps:
+      - name: Check docker image and run container
+        run: |
+          container_name=${TASK}-$(date +%Y%m%d-%H%M%S)
+          echo "container_name=${container_name}" >> ${{ github.env }}
+          docker pull $docker_image
+          docker run -d -t --gpus all --name ${container_name} \
+            -v "/dev/shm:/dev/shm"  \
+            -v ${{ github.workspace }}/../../..:${{ github.workspace }}/../../.. \
+            -v ${{ github.workspace }}/../../../proxy:/root/proxy \
+            -v ${{ github.workspace }}/../../../.cache:/root/.cache \
+            -v ${{ github.workspace }}:/paddle \
+            -e BRANCH \
+            -e PR_ID \
+            -e COMMIT_ID \
+            -e work_dir \
+            -e PADDLE_ROOT \
+            -e ci_scripts \
+            -e CACHE_DIR \
+            -e no_proxy \
+            -e CI_name \
+            -e PIP_CACHE_DIR \
+            -w /paddle --network host ${docker_image}
+
+      - name: Clone PaddleFleet
+        run: |
+          docker exec -t ${{ env.container_name }} /bin/bash -c '
+          rm -rf * .[^.]*
+          set -e
+          source /root/proxy
+          git clone https://github.com/PaddlePaddle/PaddleFleet.git .
+          git config --global --add safe.directory /paddle
+          git config pull.rebase false
+          git pull --no-edit origin pull/${PR_ID}/head
+          mkdir -p /root/.cache/pip
+          pip cache dir
+          echo "Install uv"
+          pip install -q uv
+          echo "uv sync"
+          uv sync > /dev/null 2>&1
           '
 
       - name: Multi-card test
@@ -105,29 +166,13 @@ jobs:
           docker exec -t ${{ env.container_name }} /bin/bash -c '
           bash ci/multi-card_test.sh
           multi_card_exit_code=$?
-          echo "multi_card_exit_code=$multi_card_exit_code" >> ${{ github.env }}
-          '
-
-      - name: Test summary
-        if: steps.check-bypass.outputs.can-skip != 'true'
-        env:
-          single_card_exit_code: ${{ env.single_card_exit_code }}
-          multi_card_exit_code: ${{ env.multi_card_exit_code }}
-        run: |
-          exit_code=0
-          if [[ "$single_card_exit_code" != "0" ]]; then
-            echo -e "::error:: Single card test failed, please check the '\033[34mSingle card test\033[0m' step."
-            exit_code=1
-          else
-            echo -e "\033[32mSingle card test succeeded.\033[0m"
-          fi
           if [[ "$multi_card_exit_code" != "0" ]]; then
-            echo -e "::error:: Multi card test failed, please check the '\033[34mMulti card test\033[0m' step."
-            exit_code=1
+            echo -e "::error:: \033[31mMulti card test failed.\033[0m"
+            exit 1
           else
             echo -e "\033[32mMulti card test succeeded.\033[0m"
           fi
-          exit $exit_code
+          '
 
       - name: Terminate and delete the container
         if: ${{ steps.check-bypass.outputs.can-skip != 'true' && always() }}
