add sft+lora

diff --git a/.github/workflows/Test.yml b/.github/workflows/Test.yml
--- a/.github/workflows/Test.yml
+++ b/.github/workflows/Test.yml
@@ -388,7 +388,7 @@ jobs:
           mkdir -p /workspace/PaddleFleet/coveragedata-single
           export COVERAGE_FILE=/workspace/PaddleFleet/coveragedata-single/.coverage
           export COVERAGE_RCFILE=/workspace/PaddleFleet/ci/.coveragerc
-          bash -x PaddleFleet/ci/integration_test/glm45_single_card.sh
+          bash -x PaddleFleet/ci/integration_test/glm45_pt_single_card.sh
           glm45_single_card_exit_code=$?
           ls -a /workspace/PaddleFleet/coveragedata-single
           source /workspace/PaddleFleet/.venv/bin/activate
@@ -533,21 +533,45 @@ jobs:
           python -c "import paddle; print(paddle.version.commit)"
           '
 
-      - name: Integration test (GLM4.5 multi-card)
+      - name: GLM4.5 pre-train
         if: (success() || failure()) && steps.formers_install.conclusion == 'success'
         run: |
           docker exec -t ${{ env.container_name }} /bin/bash -ce '
           source /root/proxy
-          mkdir -p /workspace/PaddleFleet/coveragedata-multi
-          export COVERAGE_FILE=/workspace/PaddleFleet/coveragedata-multi/.coverage
+          mkdir -p /workspace/PaddleFleet/coveragedata-multi-pt
+          export COVERAGE_FILE=/workspace/PaddleFleet/coveragedata-multi-pt/.coverage
           export COVERAGE_RCFILE=/workspace/PaddleFleet/ci/.coveragerc
-          bash -x PaddleFleet/ci/integration_test/glm45.sh
+          bash -x PaddleFleet/ci/integration_test/glm45_pt.sh
           glm45_exit_code=$?
           ls -a /workspace/PaddleFleet/coveragedata-multi
           source /workspace/PaddleFleet/.venv/bin/activate
           uv run coverage --version
           uv run coverage combine
-          uv run coverage xml -o /workspace/PaddleFleet/coveragedata-multi/coverage.xml
+          uv run coverage xml -o /workspace/PaddleFleet/coveragedata-multi-pt/coverage.xml
+          uv run coverage report -m
+          if [[ "$glm45_exit_code" != "0" ]]; then
+            echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
+            exit 1
+          else
+            echo -e "\033[32mIntegration test succeeded: GLM4.5.\033[0m"
+          fi
+          '
+
+      - name: GLM4.5 sft+lora
+        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
+        run: |
+          docker exec -t ${{ env.container_name }} /bin/bash -ce '
+          source /root/proxy
+          mkdir -p /workspace/PaddleFleet/coveragedata-multi-sft
+          export COVERAGE_FILE=/workspace/PaddleFleet/coveragedata-multi-sft/.coverage
+          export COVERAGE_RCFILE=/workspace/PaddleFleet/ci/.coveragerc
+          bash -x PaddleFleet/ci/integration_test/glm45_sft.sh
+          glm45_exit_code=$?
+          ls -a /workspace/PaddleFleet/coveragedata-multi
+          source /workspace/PaddleFleet/.venv/bin/activate
+          uv run coverage --version
+          uv run coverage combine
+          uv run coverage xml -o /workspace/PaddleFleet/coveragedata-multi-sft/coverage.xml
           uv run coverage report -m
           if [[ "$glm45_exit_code" != "0" ]]; then
             echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
@@ -588,11 +612,14 @@ jobs:
             https://paddle-qa.bj.bcebos.com/CodeSync/develop/PaddlePaddle/PaddleTest/tools/bos_tools.py \
             -O bos_tools.py
           push_file=$(realpath bos_tools.py)
-          cp /workspace/PaddleFleet/coveragedata-multi/coverage.xml coverage-multi.xml
+          cp /workspace/PaddleFleet/coveragedata-multi-pt/coverage.xml coverage-multi-pt.xml
+          cp /workspace/PaddleFleet/coveragedata-multi-sft/coverage.xml coverage-multi-sft.xml
           cp /workspace/PaddleFleet/coveragedata-multi-fp8/coverage.xml coverage-multi-fp8.xml
-          target_path_multi="paddle-github-action/${GITHUB_REPO_NAME}/pull/${PR_ID}/${GITHUB_SHA}/h20-multi"
+          target_path_multi_pt="paddle-github-action/${GITHUB_REPO_NAME}/pull/${PR_ID}/${GITHUB_SHA}/h20-multi-pt"
+          target_path_multi_sft="paddle-github-action/${GITHUB_REPO_NAME}/pull/${PR_ID}/${GITHUB_SHA}/h20-multi-sft"
           target_path_multi_fp8="paddle-github-action/${GITHUB_REPO_NAME}/pull/${PR_ID}/${GITHUB_SHA}/h20-multi-fp8"
-          uv run ${push_file} coverage-multi.xml ${target_path_multi}
+          uv run ${push_file} coverage-multi-pt.xml ${target_path_multi_pt}
+          uv run ${push_file} coverage-multi-sft.xml ${target_path_multi_sft}
           uv run ${push_file} coverage-multi-fp8.xml ${target_path_multi_fp8}
           '
 
@@ -686,19 +713,19 @@ jobs:
           python -c "import paddle; print(paddle.version.commit)"
           '
 
-      - name: Integration test (GLM4.5)
+      - name: GLM4.5 pre-train
         run: |
           docker exec -t ${{ env.container_name }} /bin/bash -ce '
           source /root/proxy
           source /root/proxy
-          export COVERAGE_FILE=/workspace/PaddleFleet/coveragedata/.coverage
+          export COVERAGE_FILE=/workspace/PaddleFleet/coveragedata-pt/.coverage
           export COVERAGE_RCFILE=/workspace/PaddleFleet/ci/.coveragerc
-          bash -x PaddleFleet/ci/integration_test/glm45_a100.sh
+          bash -x PaddleFleet/ci/integration_test/glm45_pt_a100.sh
           glm45_exit_code=$?
           ls -a /workspace/PaddleFleet/coveragedata
           source /workspace/PaddleFleet/.venv/bin/activate
           uv run coverage combine
-          uv run coverage xml -o /workspace/PaddleFleet/coveragedata/coverage.xml
+          uv run coverage xml -o /workspace/PaddleFleet/coveragedata-pt/coverage.xml
           uv run coverage report -m
           if [[ "$glm45_exit_code" != "0" ]]; then
             echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
@@ -707,6 +734,29 @@ jobs:
             echo -e "\033[32mIntegration test succeeded: GLM4.5.\033[0m"
           fi
           '
+
+      - name: GLM4.5 sft+lora
+        run: |
+          docker exec -t ${{ env.container_name }} /bin/bash -ce '
+          source /root/proxy
+          source /root/proxy
+          export COVERAGE_FILE=/workspace/PaddleFleet/coveragedata-sft/.coverage
+          export COVERAGE_RCFILE=/workspace/PaddleFleet/ci/.coveragerc
+          bash -x PaddleFleet/ci/integration_test/glm45_sft.sh
+          glm45_exit_code=$?
+          ls -a /workspace/PaddleFleet/coveragedata
+          source /workspace/PaddleFleet/.venv/bin/activate
+          uv run coverage combine
+          uv run coverage xml -o /workspace/PaddleFleet/coveragedata-sft/coverage.xml
+          uv run coverage report -m
+          if [[ "$glm45_exit_code" != "0" ]]; then
+            echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
+            exit 1
+          else
+            echo -e "\033[32mIntegration test succeeded: GLM4.5.\033[0m"
+          fi
+          '
+
       - name: A100 Coverage Upload to BOS
         run: |
           docker exec -t ${{ env.container_name }} /bin/bash -xce '
@@ -714,9 +764,12 @@ jobs:
             https://paddle-qa.bj.bcebos.com/CodeSync/develop/PaddlePaddle/PaddleTest/tools/bos_tools.py \
             -O bos_tools.py
           push_file=$(realpath bos_tools.py)
-          cp /workspace/PaddleFleet/coveragedata/coverage.xml coverage.xml
-          target_path="paddle-github-action/${GITHUB_REPO_NAME}/pull/${PR_ID}/${GITHUB_SHA}/a100"
-          uv run ${push_file} coverage.xml ${target_path}
+          cp /workspace/PaddleFleet/coveragedata-pt/coverage.xml coverage-a-pt.xml
+          cp /workspace/PaddleFleet/coveragedata-sft/coverage.xml coverage-a-sft.xml
+          target_path_pt="paddle-github-action/${GITHUB_REPO_NAME}/pull/${PR_ID}/${GITHUB_SHA}/a100-pt"
+          target_path_sft="paddle-github-action/${GITHUB_REPO_NAME}/pull/${PR_ID}/${GITHUB_SHA}/a100-sft"
+          uv run ${push_file} coverage-a-pt.xml ${target_path_pt}
+          uv run ${push_file} coverage-a-sft.xml ${target_path_sft}
           '
 
       - name: Terminate and delete the container
