fix

diff --git a/.github/workflows/test_paddle_dev.yml b/.github/workflows/test_paddle_dev.yml
--- a/.github/workflows/test_paddle_dev.yml
+++ b/.github/workflows/test_paddle_dev.yml
@@ -92,6 +92,7 @@ jobs:
           git config user.name "PaddleCI"
           git config user.email "paddle_ci@example.com"
           git config pull.rebase false
+          export repo_flag="paddlefleet"
           VERSION="0.1.0.dev$(date +%Y%m%d)"
           python -m pip install --pre "paddlefleet<=${VERSION}"  paddlefleet --index-url https://www.paddlepaddle.org.cn/packages/nightly/cu129/ --extra-index-url https://pypi.tuna.tsinghua.edu.cn/simple --extra-index-url https://www.paddlepaddle.org.cn/packages/stable/cu129/
           wget $paddle_url
@@ -118,88 +119,89 @@ jobs:
           docker exec -t ${{ env.container_name }} /bin/bash -c 'bash ci/clean_uv_cache.sh; rm -rf * .[^.]*'
           docker rm -f ${{ env.container_name }}
 
-  # multi-card_test:
-  #   name: Unit test (multi-card)
-  #   runs-on:
-  #     group: Fleet-H-multi-card
-  #   env:
-  #     PIP_CACHE_DIR: /home/.cache/pip
-  #     TASK: paddlefleet-CE-CUDA129-DEV-multi-card_test-release
-  #   steps:
-  #     - name: Check docker image and run container
-  #       run: |
-  #         container_name=${TASK}-$(date +%Y%m%d-%H%M%S)
-  #         echo "container_name=${container_name}" >> ${{ github.env }}
-  #         docker pull $docker_image
-  #         docker run -d -t --gpus all --name ${container_name} \
-  #           -v "/dev/shm:/dev/shm"  \
-  #           -v ${{ github.workspace }}/../../..:${{ github.workspace }}/../../.. \
-  #           -v ${{ github.workspace }}/../../..:/root \
-  #           -v /ssd1/paddle-1/action_cache:/home/.cache \
-  #           -v ${{ github.workspace }}:/paddle \
-  #           -e BRANCH \
-  #           -e PR_ID \
-  #           -e COMMIT_ID \
-  #           -e PADDLE_ROOT \
-  #           -e ci_scripts \
-  #           -e CACHE_DIR \
-  #           -e no_proxy \
-  #           -e paddle_url \
-  #           -e CI_name \
-  #           -e PIP_CACHE_DIR \
-  #           -e work_dir \
-  #           -e GITHUB_SHA="${{ github.event.pull_request.head.sha }}" \
-  #           -e GITHUB_HEAD_REF="${{ github.head_ref }}" \
-  #           -e GITHUB_REPO_NAME="${{ github.repository }}" \
-  #           -e GITHUB_EVENT_NAME="${{ github.event_name }}" \
-  #           -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
-  #           -e GITHUB_RUN_ID="${{ github.run_id }}" \
-  #           -w /paddle --network host ${docker_image}
+  multi-card_test:
+    name: Unit test (multi-card)
+    runs-on:
+      group: Fleet-H-multi-card
+    env:
+      PIP_CACHE_DIR: /home/.cache/pip
+      TASK: paddlefleet-CE-CUDA129-DEV-multi-card_test-release
+    steps:
+      - name: Check docker image and run container
+        run: |
+          container_name=${TASK}-$(date +%Y%m%d-%H%M%S)
+          echo "container_name=${container_name}" >> ${{ github.env }}
+          docker pull $docker_image
+          docker run -d -t --gpus all --name ${container_name} \
+            -v "/dev/shm:/dev/shm"  \
+            -v ${{ github.workspace }}/../../..:${{ github.workspace }}/../../.. \
+            -v ${{ github.workspace }}/../../..:/root \
+            -v /ssd1/paddle-1/action_cache:/home/.cache \
+            -v ${{ github.workspace }}:/paddle \
+            -e BRANCH \
+            -e PR_ID \
+            -e COMMIT_ID \
+            -e PADDLE_ROOT \
+            -e ci_scripts \
+            -e CACHE_DIR \
+            -e no_proxy \
+            -e paddle_url \
+            -e CI_name \
+            -e PIP_CACHE_DIR \
+            -e work_dir \
+            -e GITHUB_SHA="${{ github.event.pull_request.head.sha }}" \
+            -e GITHUB_HEAD_REF="${{ github.head_ref }}" \
+            -e GITHUB_REPO_NAME="${{ github.repository }}" \
+            -e GITHUB_EVENT_NAME="${{ github.event_name }}" \
+            -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
+            -e GITHUB_RUN_ID="${{ github.run_id }}" \
+            -w /paddle --network host ${docker_image}
 
-  #     - name: Install PaddleFleet
-  #       run: |
-  #         docker exec -t ${{ env.container_name }} /bin/bash -ce '
-  #         rm -rf * .[^.]*
-  #         source /root/proxy
-  #         pip install --upgrade pip
-  #         git clone https://github.com/PaddlePaddle/PaddleFleet.git .
-  #         git config --global --add safe.directory /paddle
-  #         git config user.name "PaddleCI"
-  #         git config user.email "paddle_ci@example.com"
-  #         git config pull.rebase false
-  #         git submodule update --init --recursive
-  #         VERSION="0.1.0.dev$(date +%Y%m%d)"
-  #         python -m pip install --pre "paddlefleet<=${VERSION}" --index-url https://www.paddlepaddle.org.cn/packages/nightly/cu129/ --extra-index-url https://pypi.tuna.tsinghua.edu.cn/simple --extra-index-url https://www.paddlepaddle.org.cn/packages/stable/cu129/
-  #         wget $paddle_url
-  #         pip install paddlepaddle_gpu-0.0.0-cp310-cp310-linux_x86_64.whl --index-url=https://www.paddlepaddle.org.cn/packages/nightly/cu129/ --force-reinstall --no-cache-dir
-  #         wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
-  #         chmod +x /usr/local/bin/yq
-  #         '
+      - name: Install PaddleFleet
+        run: |
+          docker exec -t ${{ env.container_name }} /bin/bash -ce '
+          rm -rf * .[^.]*
+          source /root/proxy
+          pip install --upgrade pip
+          git clone https://github.com/PaddlePaddle/PaddleFleet.git .
+          git config --global --add safe.directory /paddle
+          git config user.name "PaddleCI"
+          git config user.email "paddle_ci@example.com"
+          git config pull.rebase false
+          git submodule update --init --recursive
+          VERSION="0.1.0.dev$(date +%Y%m%d)"
+          export repo_flag="paddlefleet"
+          python -m pip install --pre "paddlefleet<=${VERSION}" --index-url https://www.paddlepaddle.org.cn/packages/nightly/cu129/ --extra-index-url https://pypi.tuna.tsinghua.edu.cn/simple --extra-index-url https://www.paddlepaddle.org.cn/packages/stable/cu129/
+          wget $paddle_url
+          pip install paddlepaddle_gpu-0.0.0-cp310-cp310-linux_x86_64.whl --index-url=https://www.paddlepaddle.org.cn/packages/nightly/cu129/ --force-reinstall --no-cache-dir
+          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
+          chmod +x /usr/local/bin/yq
+          '
 
-  #     - name: Multi-card test
-  #       run: |
-  #         docker exec -t ${{ env.container_name }} /bin/bash -ce '
-  #         echo "Paddle Commit"
-  #         python -c "import paddle; print(paddle.version.commit)"
-  #         echo "PaddleFleet Commit"
-  #         python -c "import paddlefleet; print(paddlefleet.version.commit)"
-  #         export PYTHONPATH=/paddle:$PYTHONPATH
-  #         bash ci/multi-card_test.sh
-  #         multi_card_exit_code=$?
-  #         if [[ "$multi_card_exit_code" != "0" ]]; then
-  #           echo -e "::error:: \033[31mMulti card test failed.\033[0m"
-  #           exit 1
-  #         else
-  #           echo -e "\033[32mMulti card test succeeded.\033[0m"
-  #         fi
-  #         '
+      - name: Multi-card test
+        run: |
+          docker exec -t ${{ env.container_name }} /bin/bash -ce '
+          echo "Paddle Commit"
+          python -c "import paddle; print(paddle.version.commit)"
+          echo "PaddleFleet Commit"
+          python -c "import paddlefleet; print(paddlefleet.version.commit)"
+          export PYTHONPATH=/paddle:$PYTHONPATH
+          bash ci/multi-card_test.sh
+          multi_card_exit_code=$?
+          if [[ "$multi_card_exit_code" != "0" ]]; then
+            echo -e "::error:: \033[31mMulti card test failed.\033[0m"
+            exit 1
+          else
+            echo -e "\033[32mMulti card test succeeded.\033[0m"
+          fi
+          '
 
-  #     - name: Terminate and delete the container
-  #       if: ${{ always() }}
-  #       run: |
-  #         set +e
-  #         docker exec -t ${{ env.container_name }} /bin/bash -c 'bash ci/clean_uv_cache.sh; rm -rf * .[^.]*'
-  #         docker rm -f ${{ env.container_name }}
+      - name: Terminate and delete the container
+        if: ${{ always() }}
+        run: |
+          set +e
+          docker exec -t ${{ env.container_name }} /bin/bash -c 'bash ci/clean_uv_cache.sh; rm -rf * .[^.]*'
+          docker rm -f ${{ env.container_name }}
 
 
   # integration-test-H20-single-card:
